import { createContext } from "react";
import logo from "../assets/company_logo.png";
let companyData = [
  {
    id: 1,
    img: logo,
    name: "Tech Company",
    rate: 4.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ut labore et...",
    openjobsnum: 50,
    employeesnum: 1.234,
    Salaries: 88.1,
    companyScope: "Global",
    companyStatus: "Hiring",
    categorey: "UI/UX Designer",
    size: "1 - 50",
    salary: "$10 - $100",
    views: 1250,
    hiringSuccess: 82,
        reviews: 92,
    ratings: 4.2,
        Address: "Giza, Egypt",
  },
  {
    id: 2,
    img: logo,
    name: "Tech Company",
    rate: 4.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, do eiusmod ut labore et ...",
    openjobsnum: 50,
    employeesnum: 1.234,
    Salaries: 88.1,
    companyScope: "Global",
    companyStatus: "Hiring",
    categorey: "Project Manager",
    size: "51 - 200",
    salary: "$10 - $100",
    views: 2500,
    hiringSuccess: 200,
      reviews: 69,
    ratings: 5.0,
        Address: "Smart Village, Giza, Egypt",
  },
  {
    id: 3,
    img: logo,
    name: "Tech Company",
    rate: 4.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ut labore et...",
    openjobsnum: 50,
    employeesnum: 1.234,
    Salaries: 88.1,
    companyScope: "Global",
    companyStatus: "Hiring",
    categorey: "Project Manager",
    size: "51 - 200",
    salary: "$100 - $1,000",
    views: 2500,
    hiringSuccess: 200,
      reviews: 69,
    ratings: 5.0,
        Address: "Smart Village, Giza, Egypt",
  },
  {
    id: 4,
    img: logo,
    name: "Tech Company",
    rate: 4.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ut labore et...",
    openjobsnum: 50,
    employeesnum: 1.234,
    Salaries: 88.1,
    companyScope: "Global",
    companyStatus: "Hiring",
    categorey: "Software Developer",
    size: "51 - 200",
    salary: "$1,000 - $10,000",
    views: 1250,
    hiringSuccess: 82,
      reviews: 69,
    ratings: 5.0,
        Address: "Smart Village, Giza, Egypt",
  },
  {
    id: 5,
    img: logo,
    name: "Tech Company",
    rate: 4.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ut labore et...",
    openjobsnum: 50,
    employeesnum: 1.234,
    Salaries: 88.1,
    companyScope: "Global",
    companyStatus: "Hiring",
    categorey: "Software Developer",
    size: "201 - 500",
    salary: "$1,000 - $10,000",
    views: 250,
    hiringSuccess: 65,
        reviews: 128,
    ratings: 4.8,
        Address: "Smart Village, Giza, Egypt",
  },
  {
    id: 6,
    img: logo,
    name: "Tech Company",
    rate: 4.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ut labore et...",
    openjobsnum: 50,
    employeesnum: 1.234,
    Salaries: 88.1,
    companyScope: "Global",
    companyStatus: "Hiring",
    categorey: "Software Tester",
    size: "501 - 1000",
    salary: "$10,000 - $100,000",
    views: 1250,
    hiringSuccess: 82,
        reviews: 128,
    ratings: 4.8,
        Address: "Smart Village, Giza, Egypt",
  },
  {
    id: 7,
    img: logo,
    name: "Tech Company",
    rate: 4.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ut labore et...",
    openjobsnum: 50,
    employeesnum: 1.234,
    Salaries: 88.1,
    companyScope: "Global",
    companyStatus: "Hiring",
    categorey: "Software Tester",
    size: "1000+",
    salary: "$100,000 Up",
    views: 1250,
    hiringSuccess: 82,
     reviews: 128,
    ratings: 5.0,
        Address: "Smart Village, Giza, Egypt",
  },
  {
    id: 8,
    img: logo,
    name: "Tech Company",
    rate: 4.5,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ut labore et...",
    openjobsnum: 50,
    employeesnum: 1.234,
    Salaries: 88.1,
    companyScope: "Global",
    companyStatus: "Hiring",
    categorey: "Graphic Designer",
    size: "1000+",
    salary: "$100,000 Up",
    views: 2500,
    hiringSuccess: 200,
    reviews: 128,
    ratings: 5.0,
        Address: "Smart Village, Giza, Egypt",
  },
];

export const CompanyContext = createContext({});

export function CompanyProvider({ children }) {
  return (
    <CompanyContext.Provider value={{ companyData }}>
      {children}
    </CompanyContext.Provider>
  );
}
